#if canImport(PDFKit) && canImport(UIKit)
import CoreGraphics
import Foundation
import PDFKit
import UIKit

/// `PDFAnnotation` subclass that draws its own `/Highlight` appearance.
///
/// Why this exists: iOS 26 PDFKit fails to render `/Subtype /Highlight`
/// annotations added to a page at runtime — the annotation joins the
/// page's annotation list (verified via `page.annotations.count`), the
/// `/Contents` text is captured, but no quad is ever drawn on screen.
/// Same family of bug as the `/Ink` `/AP` appearance-stream issue: the
/// auto-generated `/AP` is broken (BBox local, drawing commands in
/// absolute page coords), and PDFKit's own renderer prefers `/AP` for
/// annotations marked as having one. PDFKit-rendered highlights from
/// the original PDF (loaded from disk) render fine because their `/AP`
/// was generated by a non-Apple writer.
///
/// Overriding `draw(with:in:)` makes PDFKit capture our drawing into
/// the appearance stream, so the highlight renders correctly both
/// in-app and in cross-app viewers (Preview, QuickLook, Adobe).
///
/// We render each quad as a translucent fill in multiply blend mode
/// so underlying text reads through — matching how Apple Books, Notes,
/// and Adobe display a /Highlight.
public final class PumiceHighlightAnnotation: PDFAnnotation {
    private let quads: [Quad]
    private let fillColor: UIColor
    /// Visible alpha of the fill. `/Highlight` is rendered translucently
    /// by most PDF viewers; we match that here so the highlight is
    /// legible without obliterating the text underneath.
    private let fillAlpha: CGFloat = 0.35

    public init(
        quads: [Quad],
        color: UIColor,
        bounds: CGRect
    ) {
        self.quads = quads
        self.fillColor = color
        super.init(bounds: bounds, forType: .highlight, withProperties: nil)
    }

    @available(*, unavailable)
    public required init?(coder: NSCoder) { fatalError("not used") }

    public override func draw(with box: PDFDisplayBox, in context: CGContext) {
        UIGraphicsPushContext(context)
        context.saveGState()
        context.setBlendMode(.multiply)
        fillColor.withAlphaComponent(fillAlpha).setFill()
        for quad in quads {
            let path = UIBezierPath()
            path.move(to: quad.topLeft)
            path.addLine(to: quad.topRight)
            path.addLine(to: quad.bottomRight)
            path.addLine(to: quad.bottomLeft)
            path.close()
            path.fill()
        }
        context.restoreGState()
        UIGraphicsPopContext()
    }
}

/// Builds standard PDF `/Subtype /Highlight` annotations from `Highlight`
/// values, with a deterministic `AnnotationID` stamped into the annotation's
/// `/NM` entry and the underlying text written into `/Contents` so PDF
/// readers without our Markdown extraction layer can still surface it.
public enum HighlightAnnotationBuilder {
    /// - Parameters:
    ///   - highlight: The highlight to serialize. `highlight.quads` must
    ///     already be in PDF user-space coordinates.
    ///   - uuid: UUID seeding the deterministic ID. Defaults to a fresh
    ///     UUID; callers that already track a stable identifier should
    ///     pass it in to keep `/NM` aligned across reads.
    public static func makeAnnotation(
        highlight: Highlight,
        uuid: UUID = UUID()
    ) -> PDFAnnotation {
        let bounds = HighlightGeometry.boundingRect(highlight.quads)
        let id = AnnotationID(pageIndex: highlight.pageIndex, annotationUUID: uuid)
        let annotation = PumiceHighlightAnnotation(
            quads: highlight.quads,
            color: highlight.color.rgba.uiColor,
            bounds: bounds
        )

        // PDFKit's `quadrilateralPoints` are specified relative to the
        // annotation's bounds.origin — NOT in absolute PDF user space.
        // See iPhoneOS13.0.sdk/.../PDFAnnotationUtilities.h:
        //   "Points are specified relative to the annotation's bound's
        //    origin."
        // The PDF spec is also explicit (Table 179 of ISO 32000-1):
        //   "QuadPoints array will be ignored if the specified points
        //    are outside the bounding box specified by Rect."
        // We store quads in PDF user space, so subtract bounds.origin
        // before handing them to PDFKit. This was a load-bearing bug
        // for snap-to-text: with absolute coords, PDFKit silently
        // treated the annotation as having no valid quads and never
        // rendered it (and never invoked our `draw(with:in:)` either).
        let origin = bounds.origin
        annotation.quadrilateralPoints = highlight.quads.flatMap { quad in
            [
                NSValue(cgPoint: CGPoint(x: quad.topLeft.x - origin.x, y: quad.topLeft.y - origin.y)),
                NSValue(cgPoint: CGPoint(x: quad.topRight.x - origin.x, y: quad.topRight.y - origin.y)),
                NSValue(cgPoint: CGPoint(x: quad.bottomLeft.x - origin.x, y: quad.bottomLeft.y - origin.y)),
                NSValue(cgPoint: CGPoint(x: quad.bottomRight.x - origin.x, y: quad.bottomRight.y - origin.y))
            ]
        }
        annotation.color = highlight.color.rgba.uiColor
        annotation.contents = highlight.extractedText

        // See InkAnnotationBuilder for the rationale: /NM is dropped by
        // PDFKit's writer on iOS, so we persist the deterministic ID via
        // /T (`userName`) instead.
        annotation.userName = id.stringValue

        return annotation
    }
}
#endif
